name: CI - Validação de Código com Pylint

on:
  pull_request:
    branches: [ main, master ]

jobs:
  pylint_check:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout do Código
      uses: actions/checkout@v4

    - name: 2. Configurar Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Sua versão preferida

    - name: 3. Instalar Pylint
      # INSTALAMOS O Pylint no ambiente do Runner
      run: pip install pylint

    - name: 4. Executar Pylint
      # RODAMOS o comando Pylint diretamente nos arquivos Python do projeto.
      run: pylint calculadora.py
